app = "bucketeer-backend"
primary_region = "waw"

[build]
  dockerfile = "./Dockerfile"
  build-target = "runner"

[deploy]
  strategy = "rolling"

[env]
  DATABASE_PATH = "/data/prod.db"
  NODE_ENV = "production"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "bucketeer_data"
  destination = "/data"
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
